### ISSUE TITLE
Incorrest result for vector of 1 element

### ISSUE THREAD

**Issue by vladon** [mrrusof/algorithms#1]
Pass vector of 1 element (for example, `{ 0 }`) to your function. It will return `-1`, but must return `0`.

**Comment by mrrusof** [comment]
What is "your function" ?

**Comment by vladon** [comment]
@mrrusof Sorry, it's about https://github.com/mrrusof/algorithms/blob/master/adjacent-coins/main.cpp

**Comment by mrrusof** [comment]
You are right. Please review commit e6817b314ae5486169c838eea458bb15187606fb. I claim that if `condition == 0`, then `A.size() < 2`.

**Comment by vladon** [comment]
@mrrusof Now it's incorrect for `{ 0, 0 }` :-) Must return `0`, but returns `1`.

**Comment by mrrusof** [comment]
@vladon Nice. What about now? 6a362dff513aa6a8e29418a81fa82af02b605df1

**Comment by vladon** [comment]
@mrrusof Sorry again, now it returns `0` for `{0, 1}`, but must return `1`

For `{0, 1, 0}` it returns `0`, but must return `2`...

**Comment by mrrusof** [comment]
hmmm. What about now? 51c5adbb35d908bc15b1be6d15c503d27f12b4e3

**Comment by mrrusof** [comment]
@vladon I think I fixed it. Could you please have a look?

**Comment by mrrusof** [comment]
Thank you!
